# Generated by Django 2.0.4 on 2018-04-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='translator',
        ),
        migrations.RemoveField(
            model_name='order',
            name='direction',
        ),
        migrations.AddField(
            model_name='order',
            name='direction',
            field=models.ManyToManyField(to='orders.Direction'),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
