# Generated by Django 2.0.4 on 2018-04-18 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0003_remove_translator_direction'),
        ('orders', '0002_auto_20180418_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='translated',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='translator.Translator'),
        ),
    ]
