# Generated by Django 2.0.4 on 2018-04-19 11:52

from django.db import migrations, models
import orders.utils.Utils


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_translated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='order',
            name='file',
            field=models.FileField(upload_to='orders_files/<django.db.models.fields.CharField>', validators=[orders.utils.Utils.validate_file_extension]),
        ),
    ]
