# Generated by Django 2.0.4 on 2018-04-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180419_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='urgency',
            field=models.CharField(default='2', max_length=5),
        ),
    ]
