# Generated by Django 2.0.4 on 2018-04-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180421_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pages',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='urgency',
            field=models.CharField(default='2', max_length=10),
        ),
    ]
