# Generated by Django 2.0.4 on 2018-04-18 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20180413_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='code',
        ),
    ]
