# Generated by Django 2.0.4 on 2018-04-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20180418_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='c_id',
            field=models.CharField(max_length=150),
        ),
    ]
