# Generated by Django 2.0.4 on 2018-04-18 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0002_auto_20180418_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translator',
            name='direction',
        ),
    ]
